version: '3'
services:
  backend:
    image: '${COMPANY}/${PROJECT_NAME}-backend:${VERSION}'
    build:
      context: kcal-app-express
      args:
        BASE_PATH: 'kcal-app'
        PORT: '6001'
    env_file:
      - kcal-app-express/.env
    ports:
      - '6001'
  frontend:
    image: '${COMPANY}/${PROJECT_NAME}-frontend:${VERSION}'
    build:
      context: kcal-app-react
      args:
        BASE_PATH: 'kcal-app-react'
        BACKEND_BASE_PATH: 'kcal-app'
        BACKEND_PORT: '6001'
  nginx:
    image: nginx:1.25.2-alpine-slim
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
      - frontend
    ports:
      - '80:80'
