version: '3'

services:

  database:
    image: mysql:8.2
    restart: always
    volumes:
      - ./database:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
      MYSQL_DATABASE: '${MYSQL_DATABASE}'

  adminer:
    image: adminer
    restart: always
    depends_on:
      - database
    ports:
      - '8080:8080'

  backend:
    image: '${COMPANY}/${PROJECT_NAME}-backend:${VERSION}'
    build:
      context: kcal-app-express
      args:
        BASE_PATH: 'kcal-app-backend'
        PORT: '6001'
    env_file:
      - kcal-app-express/.env
    depends_on:
      - database
    ports:
      - '6001'

  frontend:
    image: '${COMPANY}/${PROJECT_NAME}-frontend:${VERSION}'
    build:
      context: kcal-app-react
      args:
        BASE_PATH: 'kcal-app'
        BACKEND_BASE_PATH: 'kcal-app-backend'
        BACKEND_PORT: '6001'
    ports:
      - '80'

  nginx:
    image: nginx:1.25.2-alpine-slim
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - adminer
      - backend
      - frontend
    ports:
      - '80:80'
