version: '3'
services:
  backend:
    image: 'devbysp/kcal-app-backend:${TAG}'
    build:
      context: .
    ports:
      - "8080"
    environment:
      - PORT = "8080"
      - BASE_PATH = kcal-app
      - ENABLE_CORS = true
  nginx:
    image: nginx:1.25.2-alpine-slim
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
    ports:
      - "80:80"
